language: objective-c
osx_image: xcode8

xcode_project: Reflex.xcodeproj
xcode_scheme: Reflex
xcode_sdk: iphonesimulator10.0

script:
- set -o pipefail && xcodebuild -project Reflex.xcodeproj -scheme Reflex -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO -destination "platform=iOS Simulator,name=iPhone 6s" build | xcpretty
- pod lib lint

